;;; async-test.el --- Exercise Commercial Gnus's actual scheduler -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'gnus-start)
(require 'gnus-group)

(ert-deftest commercial-gnus-rss-data-declares-dynamic-binding ()
  (require 'nnrss)
  (let ((nnrss-directory (make-temp-file "gnus-rss-data-" t))
        (nnrss-group-alist '(("example" "https://example.invalid/rss" "Example")))
        (nnrss-server-data '(("example" 1)))
        (nnrss-group-data nil))
    (unwind-protect
        (progn
          (nnrss-save-server-data "")
          (nnrss-save-group-data "example" "")
          (dolist (name '("nnrss" "example"))
            (with-temp-buffer
              (insert-file-contents (nnrss-make-filename name ""))
              (should (looking-at ";; .*lexical-binding: nil;"))))
          (let (warnings)
            (cl-letf (((symbol-function 'display-warning)
                       (lambda (&rest args) (push args warnings))))
              (nnrss-read-server-data "")
              (nnrss-read-group-data "example" ""))
            (should-not warnings))
          (should (equal nnrss-server-data '(("example" 1)))))
      (delete-directory nnrss-directory t))))

(ert-deftest commercial-gnus-runtime-compilation-with-source-libraries ()
  (require 'gnus-util)
  (should (= 7 (funcall (gnus-byte-compile '(lambda () 7))))))

(ert-deftest commercial-gnus-refresh-includes-foreign-group-methods ()
  (let* ((gnus-background-get-unread-articles nil)
         (gnus-select-method '(nnnil ""))
         (gnus-select-methods '((nnnil "")))
         (gnus-activate-level 2)
         (gnus-activate-foreign-newsgroups 2)
         (method '(nnatom "test-feed"))
         (info (gnus-info-make "nnatom+test-feed:example" 2 nil nil method))
         (gnus-newsrc-alist (list 'dummy info))
         (received nil))
    (cl-letf (((symbol-function 'gnus-thread-group-running-p) #'ignore)
              ((symbol-function 'gnus-find-method-for-group) (lambda (&rest _) method))
              ((symbol-function 'gnus-similar-server-opened) #'ignore)
              ((symbol-function 'gnus-get-function) (lambda (&rest _) #'ignore))
              ((symbol-function 'gnus-archive-server-wanted-p) #'ignore)
              ((symbol-function 'gnus-get-unread-articles--doit)
               (lambda (methods _level) (setq received methods))))
      (gnus-get-unread-articles 2)
      (should (equal (cdr (assoc method received)) (list info))))))

(ert-deftest commercial-gnus-refresh-yields-and-finishes ()
  ;; Keep the real gnus-get-unread-articles, scheduler and method runner.
  ;; Simulate a network wait at the backend boundary, without user state.
  (let* ((gnus-background-get-unread-articles t)
         (gnus-select-method '(nnnil ""))
         (gnus-select-methods '((nnnil "")))
         (gnus-newsrc-alist '(dummy))
         (gnus-group-list-mode '(2))
         (heartbeats 0)
         (done nil)
         (backend-started nil)
         (saved-hooks (default-value 'gnus-after-getting-new-news-hook))
         (timer (run-at-time 0 0.02 (lambda () (cl-incf heartbeats)))))
    (unwind-protect
        (progn
          ;; GNU Emacs threads do not inherit a caller's dynamic bindings.
          (set-default 'gnus-after-getting-new-news-hook
                       (list (lambda () (setq done t))))
        (cl-letf (((symbol-function 'gnus-get-function) (lambda (&rest _) #'ignore))
                  ((symbol-function 'gnus-check-backend-function) (lambda (&rest _) nil))
                  ((symbol-function 'gnus-method-denied-p) (lambda (&rest _) nil))
                  ((symbol-function 'gnus-open-server) (lambda (&rest _) t))
                  ((symbol-function 'gnus-group-list-groups) (lambda (&rest _) nil))
                  ((symbol-function 'gnus-read-active-for-groups)
                   (lambda (&rest _)
                     (setq backend-started t)
                     (let ((process (make-process :name "commercial-test-wait"
                                                  :command '("sleep" "0.4")
                                                  :noquery t)))
                       (while (process-live-p process)
                         (accept-process-output process 0.05)))))
                  ((symbol-function 'gnus-archive-server-wanted-p) (lambda () nil)))
          (let ((start (float-time)))
            (gnus-get-unread-articles 2)
            (should (< (- (float-time) start) 0.2)))
          (let ((deadline (+ (float-time) 5)))
            (while (and (not done) (< (float-time) deadline))
              (accept-process-output nil 0.02)))
          (should backend-started)
          (should done)
          (should (> heartbeats 5))
          (princ (format "MAIN-LOOP-HEARTBEATS %d\n" heartbeats))))
      (set-default 'gnus-after-getting-new-news-hook saved-hooks)
      (cancel-timer timer))))

(ert-deftest commercial-gnus-registered-server-respects-group-level ()
  (let* ((gnus-background-get-unread-articles nil)
         (gnus-select-method '(nnnil ""))
         (method '(nnatom "test-feed"))
         (gnus-select-methods (list gnus-select-method method))
         (gnus-activate-level 2)
         (gnus-activate-foreign-newsgroups 2)
         (info (gnus-info-make "nnatom+test-feed:example" 7 nil nil method))
         (gnus-newsrc-alist (list 'dummy info))
         (gnus-newsrc-hashtb (make-hash-table :test 'equal))
         (gnus-active-hashtb (make-hash-table :test 'equal))
         (received nil))
    (cl-letf (((symbol-function 'gnus-thread-group-running-p) #'ignore)
              ((symbol-function 'gnus-find-method-for-group) (lambda (&rest _) method))
              ((symbol-function 'gnus-similar-server-opened) #'ignore)
              ((symbol-function 'gnus-get-function) (lambda (&rest _) #'ignore))
              ((symbol-function 'gnus-archive-server-wanted-p) #'ignore)
              ((symbol-function 'gnus-get-unread-articles--doit)
               (lambda (methods _level) (setq received methods))))
      (gnus-get-unread-articles 2)
      (should-not (assoc method received))
      (setf (gnus-info-level info) 2)
      (gnus-get-unread-articles 2)
      (should (equal (cdr (assoc method received)) (list info))))))

(ert-deftest commercial-gnus-libraries-come-from-one-tree ()
  (dolist (feature '(gnus gnus-start gnus-group gnus-sum message mm-decode nnheader))
    (require feature)
    (should (file-in-directory-p (symbol-file feature 'provide)
                                (file-name-directory (locate-library "gnus-start"))))))

(ert-deftest commercial-gnus-feed-parses-one-group-with-gnu-cons ()
  (require 'nnfeed)
  (let ((nnfeed-servers (make-hash-table :test 'equal))
        (nnfeed-group-names (make-hash-table :test 'equal))
        (nnfeed-backend 'nnatom)
        (nnfeed-read-feed-function (lambda (&rest _) '(feed-data)))
        (nnfeed-read-title-function (lambda (_) "example"))
        (nnfeed-read-description-function #'ignore)
        (nnfeed-read-group-author-function #'ignore)
        (nnfeed-read-article-function (lambda (&rest _) nil)))
    (cl-letf (((symbol-function 'nnfeed--server-address) #'identity)
              ((symbol-function 'nnfeed--read-server) #'ignore)
              ((symbol-function 'gnus-get-info) #'ignore))
      (let ((result (nnfeed--parse-feed "test-feed" "example")))
        (should (hash-table-p result))
        (should (equal (aref (gethash "example" result) 0) "example"))))))

(ert-deftest commercial-gnus-message-editing-flushes-syntax-cache ()
  (require 'message)
  (with-temp-buffer
    (message-mode)
    (insert "Subject: Test\n\nBody")
    (should (memq #'syntax-ppss-flush-cache before-change-functions))))

(ert-deftest commercial-gnus-display-predicate-without-agent ()
  (require 'gnus-sum)
  (let ((gnus-agent nil)
        (gnus-summary-display-cache nil))
    (should (functionp (gnus-summary-display-make-predicate '(unread))))))

(ert-deftest commercial-gnus-modern-atom-text ()
  (require 'nnatom)
  (should (equal (nnatom--dom-line '(title nil "Hello " (b nil "world"))) "Hello world"))
  (should (equal (car (nnatom--read-part '(content nil "<b>bold</b>") "html")) "<b>bold</b>")))

(ert-deftest commercial-gnus-modern-calendar-preserves-event-contract ()
  (require 'gnus-icalendar)
  (with-temp-buffer
    (insert "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Test//EN\nMETHOD:REQUEST\nBEGIN:VEVENT\nUID:test\nDTSTART:20261004T120000Z\nDTEND:20261004T130000Z\nSUMMARY:Meet\\, discuss\nDESCRIPTION:First\\n\n second\nORGANIZER:mailto:host@example.invalid\nATTENDEE;CN=Alice;RSVP=TRUE:mailto:alice@example.invalid\nATTENDEE;CN=Bob;ROLE=OPT-PARTICIPANT:mailto:bob@example.invalid\nRRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE\nEND:VEVENT\nEND:VCALENDAR\n")
    (let ((event (gnus-icalendar-event-from-buffer (current-buffer) '("alice@example.invalid"))))
      (should (equal (gnus-icalendar-event:summary event) "Meet, discuss"))
      (should (equal (gnus-icalendar-event:description event) "First\nsecond"))
      (should (equal (gnus-icalendar-event:req-participants event) '("Alice")))
      (should (equal (gnus-icalendar-event:opt-participants event) '("Bob")))
      (should (gnus-icalendar-event:rsvp event))
      (should (eq (gnus-icalendar-event:participation-type event) 'required))
      (should (equal (gnus-icalendar-event:recurring-freq event) "WEEKLY"))
      (should (equal (gnus-icalendar-event:recurring-interval event) "2"))
      (should (equal (gnus-icalendar-event:recurring-days event) '(1 3)))
      (should (equal (format-time-string "%FT%TZ" (gnus-icalendar-event:start-time event) t) "2026-10-04T12:00:00Z")))))

(ert-deftest commercial-gnus-modern-calendar-empty ()
  (require 'gnus-icalendar)
  (with-temp-buffer
    (insert "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Test//EN\nEND:VCALENDAR\n")
    (should-not (gnus-icalendar-event-from-buffer (current-buffer)))))

(ert-deftest commercial-gnus-smtp-transport-keeps-hook-and-server ()
  (require 'message)
  (require 'smtpmail)
  (let* ((hooks 0) received
        (message-send-mail-hook (list (lambda () (cl-incf hooks)))))
    (cl-letf (((symbol-function 'message-field-value) (lambda (_) "smtp example.invalid 465 alice"))
              ((symbol-function 'message-remove-header) #'ignore)
              ((symbol-function 'smtpmail-send-it)
               (lambda () (setq received (list smtpmail-smtp-server smtpmail-smtp-service smtpmail-smtp-user smtpmail-stream-type)))))
      (message-multi-smtp-send-mail)
      (should (= hooks 1))
      (should (equal received '("example.invalid" 465 "alice" tls))))))
