;;; async-test.el --- Exercise Commercial Gnus's actual scheduler -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'gnus-start)
(require 'gnus-group)

(ert-deftest commercial-gnus-rss-data-declares-dynamic-binding ()
  (require 'nnrss)
  (let ((nnrss-directory (make-temp-file "gnus-rss-data-" t))
        (nnrss-group-alist '(("example" "https://example.invalid/rss" "Example")))
        (nnrss-server-data '(("example" 1)))
        (nnrss-group-data nil))
    (unwind-protect
        (progn
          (nnrss-save-server-data "")
          (nnrss-save-group-data "example" "")
          (dolist (name '("nnrss" "example"))
            (with-temp-buffer
              (insert-file-contents (nnrss-make-filename name ""))
              (should (looking-at ";; .*lexical-binding: nil;"))))
          (let (warnings)
            (cl-letf (((symbol-function 'display-warning)
                       (lambda (&rest args) (push args warnings))))
              (nnrss-read-server-data "")
              (nnrss-read-group-data "example" ""))
            (should-not warnings))
          (should (equal nnrss-server-data '(("example" 1)))))
      (delete-directory nnrss-directory t))))

(ert-deftest commercial-gnus-runtime-compilation-with-source-libraries ()
  (require 'gnus-util)
  (should (= 7 (funcall (gnus-byte-compile '(lambda () 7))))))

(ert-deftest commercial-gnus-refresh-includes-foreign-group-methods ()
  (let* ((gnus-background-get-unread-articles nil)
         (gnus-select-method '(nnnil ""))
         (gnus-select-methods '((nnnil "")))
         (gnus-activate-level 2)
         (gnus-activate-foreign-newsgroups 2)
         (method '(nnatom "test-feed"))
         (info (gnus-info-make "nnatom+test-feed:example" 2 nil nil method))
         (gnus-newsrc-alist (list 'dummy info))
         (received nil))
    (cl-letf (((symbol-function 'gnus-thread-group-running-p) #'ignore)
              ((symbol-function 'gnus-find-method-for-group) (lambda (&rest _) method))
              ((symbol-function 'gnus-similar-server-opened) #'ignore)
              ((symbol-function 'gnus-get-function) (lambda (&rest _) #'ignore))
              ((symbol-function 'gnus-archive-server-wanted-p) #'ignore)
              ((symbol-function 'gnus-get-unread-articles--doit)
               (lambda (methods _level) (setq received methods))))
      (gnus-get-unread-articles 2)
      (should (equal (cdr (assoc method received)) (list info))))))

(ert-deftest commercial-gnus-refresh-yields-and-finishes ()
  ;; Keep the real gnus-get-unread-articles, scheduler and method runner.
  ;; Simulate a network wait at the backend boundary, without user state.
  (let* ((gnus-background-get-unread-articles t)
         (gnus-select-method '(nnnil ""))
         (gnus-select-methods '((nnnil "")))
         (gnus-newsrc-alist '(dummy))
         (gnus-group-list-mode '(2))
         (heartbeats 0)
         (done nil)
         (backend-started nil)
         (saved-hooks (default-value 'gnus-after-getting-new-news-hook))
         (timer (run-at-time 0 0.02 (lambda () (cl-incf heartbeats)))))
    (unwind-protect
        (progn
          ;; GNU Emacs threads do not inherit a caller's dynamic bindings.
          (set-default 'gnus-after-getting-new-news-hook
                       (list (lambda () (setq done t))))
        (cl-letf (((symbol-function 'gnus-get-function) (lambda (&rest _) #'ignore))
                  ((symbol-function 'gnus-check-backend-function) (lambda (&rest _) nil))
                  ((symbol-function 'gnus-method-denied-p) (lambda (&rest _) nil))
                  ((symbol-function 'gnus-open-server) (lambda (&rest _) t))
                  ((symbol-function 'gnus-group-list-groups) (lambda (&rest _) nil))
                  ((symbol-function 'gnus-read-active-for-groups)
                   (lambda (&rest _)
                     (setq backend-started t)
                     (let ((process (make-process :name "commercial-test-wait"
                                                  :command '("sleep" "0.4")
                                                  :noquery t)))
                       (while (process-live-p process)
                         (accept-process-output process 0.05)))))
                  ((symbol-function 'gnus-archive-server-wanted-p) (lambda () nil)))
          (let ((start (float-time)))
            (gnus-get-unread-articles 2)
            (should (< (- (float-time) start) 0.2)))
          (let ((deadline (+ (float-time) 5)))
            (while (and (not done) (< (float-time) deadline))
              (accept-process-output nil 0.02)))
          (should backend-started)
          (should done)
          (should (> heartbeats 5))
          (princ (format "MAIN-LOOP-HEARTBEATS %d\n" heartbeats))))
      (set-default 'gnus-after-getting-new-news-hook saved-hooks)
      (cancel-timer timer))))

(ert-deftest commercial-gnus-registered-server-respects-group-level ()
  (let* ((gnus-background-get-unread-articles nil)
         (gnus-select-method '(nnnil ""))
         (method '(nnatom "test-feed"))
         (gnus-select-methods (list gnus-select-method method))
         (gnus-activate-level 2)
         (gnus-activate-foreign-newsgroups 2)
         (info (gnus-info-make "nnatom+test-feed:example" 7 nil nil method))
         (gnus-newsrc-alist (list 'dummy info))
         (gnus-newsrc-hashtb (make-hash-table :test 'equal))
         (gnus-active-hashtb (make-hash-table :test 'equal))
         (received nil))
    (cl-letf (((symbol-function 'gnus-thread-group-running-p) #'ignore)
              ((symbol-function 'gnus-find-method-for-group) (lambda (&rest _) method))
              ((symbol-function 'gnus-similar-server-opened) #'ignore)
              ((symbol-function 'gnus-get-function) (lambda (&rest _) #'ignore))
              ((symbol-function 'gnus-archive-server-wanted-p) #'ignore)
              ((symbol-function 'gnus-get-unread-articles--doit)
               (lambda (methods _level) (setq received methods))))
      (gnus-get-unread-articles 2)
      (should-not (assoc method received))
      (setf (gnus-info-level info) 2)
      (gnus-get-unread-articles 2)
      (should (equal (cdr (assoc method received)) (list info))))))

(ert-deftest commercial-gnus-libraries-come-from-one-tree ()
  (dolist (feature '(gnus gnus-start gnus-group gnus-sum message mm-decode nnheader))
    (require feature)
    (should (file-in-directory-p (symbol-file feature 'provide)
                                commercial-gnus--directory))))

(ert-deftest commercial-gnus-feed-parses-one-group-with-gnu-cons ()
  (require 'nnfeed)
  (let ((nnfeed-servers (make-hash-table :test 'equal))
        (nnfeed-group-names (make-hash-table :test 'equal))
        (nnfeed-backend 'nnatom)
        (nnfeed-read-feed-function (lambda (&rest _) '(feed-data)))
        (nnfeed-read-title-function (lambda (_) "example"))
        (nnfeed-read-description-function #'ignore)
        (nnfeed-read-group-author-function #'ignore)
        (nnfeed-read-article-function (lambda (&rest _) nil)))
    (cl-letf (((symbol-function 'nnfeed--server-address) #'identity)
              ((symbol-function 'nnfeed--read-server) #'ignore)
              ((symbol-function 'gnus-get-info) #'ignore))
      (let ((result (nnfeed--parse-feed "test-feed" "example")))
        (should (hash-table-p result))
        (should (equal (aref (gethash "example" result) 0) "example"))))))

(ert-deftest commercial-gnus-message-editing-flushes-syntax-cache ()
  (require 'message)
  (with-temp-buffer
    (message-mode)
    (insert "Subject: Test\n\nBody")
    (should (memq #'syntax-ppss-flush-cache before-change-functions))))

(ert-deftest commercial-gnus-display-predicate-without-agent ()
  (require 'gnus-sum)
  (let ((gnus-agent nil)
        (gnus-summary-display-cache nil))
    (should (functionp (gnus-summary-display-make-predicate '(unread))))))

(ert-deftest commercial-gnus-notifications-run-on-main-thread ()
  (let* ((reported nil)
         (commercial-gnus-group-updated-hook
          (list (lambda (group) (setq reported (cons group (current-thread))))))
         worker)
    ;; Normal foreground updates are not background source completions.
    (commercial-gnus--notify-group "foreground")
    (should-not reported)
    (setq worker
          (make-thread (lambda () (commercial-gnus--notify-group "example"))
                       "gnus-get-unread-articles"))
    (let ((deadline (+ (float-time) 2)))
      (while (and (not reported) (< (float-time) deadline))
        (accept-process-output nil 0.01)))
    (thread-join worker)
    (should (equal (car reported) "example"))
    (should (eq (cdr reported) main-thread))))

(ert-deftest commercial-gnus-timer-dispatched-in-worker-defers-view ()
  (let* ((reported nil)
         (worker-finished nil)
         (saved (default-value 'commercial-gnus-group-updated-hook)))
    (unwind-protect
        (progn
          (set-default 'commercial-gnus-group-updated-hook
                       (list (lambda (_) (setq reported (current-thread)))))
          (thread-join
           (make-thread
            (lambda ()
              (commercial-gnus--run-group-hook "example")
              (setq worker-finished (not reported))) "test-view-worker"))
          (should worker-finished)
          (let ((deadline (+ (float-time) 2)))
            (while (and (not reported) (< (float-time) deadline))
              (accept-process-output nil 0.01)))
          (should (eq reported main-thread)))
      (set-default 'commercial-gnus-group-updated-hook saved))))
