;;; window-border-test.el --- Native window border regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'window-border)

(defmacro window-border-test--layout (&rest body)
  (declare (indent 0))
  `(let ((old-mode window-border-mode)
         (old-width window-border-width))
     (unwind-protect
         (save-window-excursion
           (window-border-mode -1)
           (delete-other-windows)
           (switch-to-buffer (get-buffer-create " *window-border-test*"))
           (erase-buffer)
           (dotimes (i 300) (insert (format "Line %d: border geometry\n" i)))
           (goto-char (point-min))
           (setq-local header-line-format "Header")
           (setq-local tab-line-format "Tab")
           ,@body)
       (setq window-border-width old-width)
       (window-border-mode (if old-mode 1 -1)))))

(ert-deftest window-border-native-width-validation ()
  (should-error (window-border--primitive -1))
  (should-error (window-border--primitive (expt 2 40)))
  (should-error (window-border--primitive nil)))

(ert-deftest window-border-terminal-geometry-unchanged ()
  (skip-unless (not (display-graphic-p)))
  (window-border-test--layout
    (let ((dimensions (list (window-body-width nil t)
                            (window-body-height nil t))))
      (setq window-border-width 2)
      (window-border-mode 1)
      (should (equal dimensions (list (window-body-width nil t)
                                     (window-body-height nil t)))))))

(ert-deftest window-border-gui-reserves-space-and-restores ()
  (skip-unless (display-graphic-p))
  (window-border-test--layout
    (redisplay t)
    (let ((width (window-body-width nil t))
          (height (window-body-height nil t))
          (mini-width (window-body-width (minibuffer-window) t))
          (mini-height (window-body-height (minibuffer-window) t))
          (text-height (cdr (window-text-pixel-size nil 1 25))))
      (setq window-border-width 2)
      (window-border-mode 1)
      (redisplay t)
      (should (= (window-body-width nil t) (- width 4)))
      (should (= (window-body-height nil t) (- height 4)))
      (should (= (window-body-width (minibuffer-window) t) mini-width))
      (should (= (window-body-height (minibuffer-window) t) mini-height))
      (should (= (cdr (window-text-pixel-size nil 1 25)) text-height))
      (window-border-mode -1)
      (redisplay t)
      (should (= (window-body-width nil t) width))
      (should (= (window-body-height nil t) height)))))

(ert-deftest window-border-nested-windows-scroll-resize ()
  (skip-unless (display-graphic-p))
  (window-border-test--layout
    (let* ((left (selected-window))
           (right (split-window-right))
           (below (split-window right nil 'below)))
      (setq window-border-width 2)
      (window-border-mode 1)
      (dolist (window (list left right below))
        (select-window window)
        (goto-char (point-min))
        (redisplay t)
        (let ((position (window-absolute-pixel-position 1 window))
              (edges (window-absolute-pixel-edges window)))
          (should (>= (car position) (+ (car edges) 2)))
          (should (> (cdr position) (+ (cadr edges) 2))))
        (scroll-up-command 3)
        (redisplay t))
      (adjust-window-trailing-edge left 20 t t)
      (redisplay t)
      (should (> (window-body-width below t) 0))
      (should (> (window-body-height below t) 0)))))

(ert-deftest window-border-invalid-customization-and-mode-reset ()
  (window-border-test--layout
    (dolist (width (list nil 0 -1 (1+ (max 1 (/ (frame-char-height) 2)))))
      (should-error (customize-set-variable 'window-border-width width)
                    :type 'user-error))
    (setq window-border-width 2)
    (window-border-mode 1)
    (setq window-border-width nil)
    (should-error (window-border-mode 1) :type 'user-error)
    (should-not window-border-mode)))

;;; window-border-test.el ends here
